### ISSUE TITLE
MLRepeater error

### ISSUE THREAD

**Issue by daviskregers** [rainlab/translate-plugin#216]
Hello,

I have an issue related to the repeater, it throws an error while switching languages:
`
"Call to undefined method October\Rain\Halcyon\Builder::hasRelation()" on line 776 of /Users/daviskregers/Sites/octest/vendor/october/rain/src/Halcyon/Builder.php`

Steps to replicate:

1. Installed a fresh copy of october + rainlab pages( v1.2.13 ) + translate ( v1.2.9 )
2. Added a second language
3. Changed the demo theme's default layout:

```
description = "Default layout"
[staticPage]
==

  {repeater name="slider" tab="Slider" prompt="Add more item"}
  	{variable type="richeditor" tab="Content" name="title"    label="Slider title"  }{/variable}
  	{variable type="richeditor" tab="Content" name="content"  label="Slider content"}{/variable}
  	{variable type="text" tab="Content" name="link_title"    label="Slider button title"}{/variable}
  	{variable type="text" tab="Content" name="link"    label="Slider button url"}{/variable}
  	{variable type="mediafinder" tab="Content" 	mode="image" 	name="image" label="Slider image"}{/variable}
  {/repeater}
```

4. Created a new page with the default layout and switched languages for the repeater.

Here's the trace stack:
```

BadMethodCallException: Call to undefined method October\Rain\Halcyon\Builder::hasRelation() in /Users/daviskregers/Sites/octest/vendor/october/rain/src/Halcyon/Builder.php:776
Stack trace:
#0 [internal function]: October\Rain\Halcyon\Builder->__call('hasRelation', Array)
#1 /Users/daviskregers/Sites/octest/vendor/october/rain/src/Halcyon/Model.php(1651): call_user_func_array(Array, Array)
#2 /Users/daviskregers/Sites/octest/modules/cms/classes/CmsCompoundObject.php(489): October\Rain\Halcyon\Model->__call('hasRelation', Array)
#3 /Users/daviskregers/Sites/octest/modules/backend/traits/FormModelSaver.php(58): Cms\Classes\CmsCompoundObject->__call('hasRelation', Array)
#4 /Users/daviskregers/Sites/octest/modules/backend/traits/FormModelSaver.php(35): Backend\Widgets\Form->setModelAttributes(Object(RainLab\Pages\Classes\Page), Array)
#5 /Users/daviskregers/Sites/octest/modules/backend/widgets/Form.php(326): Backend\Widgets\Form->prepareModelsToSave(Object(RainLab\Pages\Classes\Page), Array)
#6 /Users/daviskregers/Sites/octest/plugins/rainlab/translate/formwidgets/MLRepeater.php(126): Backend\Widgets\Form->setFormValues(Array)
#7 [internal function]: RainLab\Translate\FormWidgets\MLRepeater->onSwitchItemLocale()
#8 /Users/daviskregers/Sites/octest/modules/backend/classes/Controller.php(570): call_user_func_array(Array, Array)
#9 /Users/daviskregers/Sites/octest/modules/backend/classes/Controller.php(521): Backend\Classes\Controller->runAjaxHandlerForWidget(Object(RainLab\Translate\FormWidgets\MLRepeater), 'onSwitchItemLoc...')
#10 /Users/daviskregers/Sites/octest/modules/backend/classes/Controller.php(423): Backend\Classes\Controller->runAjaxHandler('formPaged41d8cd...')
#11 /Users/daviskregers/Sites/octest/modules/backend/classes/Controller.php(233): Backend\Classes\Controller->execAjaxHandlers()
#12 /Users/daviskregers/Sites/octest/modules/backend/classes/BackendController.php(106): Backend\Classes\Controller->run('index', Array)
#13 [internal function]: Backend\Classes\BackendController->run('rainlab/pages')
#14 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#15 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#16 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), 'run')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#23 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Backend\\Classes...', 'run')
#24 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /Users/daviskregers/Sites/octest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 /Users/daviskregers/Sites/octest/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 {main}
```

**Comment by daftspunk** [comment]
This will be fixed in Build 397+

Thanks!
