### ISSUE TITLE
Wrong method called by RainLab\Translate\Classes\ThemeScanner

### ISSUE THREAD

**Issue by marcomessa** [rainlab/translate-plugin#320]
Hello,
I noticed this error every time i try to update my language references in backend settings:
```
"Call to undefined method System\Models\MailTemplate::allTemplates()" on line 1419 of /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php
```
That's happening because ThemeScanner calls MailTemplate::allTemplates() (which doesn't exists)  instead of MailTemplate::listAllTemplates(). 

Although setting up the correct method name bring a different error:

"Trying to get property of non-object" on line 100 of /Users/marco/Sites/up-studio/ie/plugins/rainlab/translate/classes/ThemeScanner.php

For now, I commented line 38 in RainLab\Translate\Classes\ThemeScanner, but it may cause unexpected behavior (maybe no mails are scanned for translations?

Here is full stack trace
```
BadMethodCallException: Call to undefined method System\Models\MailTemplate::allTemplates() in /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1419
Stack trace:
#0 /Users/marco/Sites/up-studio/ie/vendor/october/rain/src/Extension/ExtendableTrait.php(393): Illuminate\Database\Eloquent\Model->__call('allTemplates', Array)
#1 /Users/marco/Sites/up-studio/ie/vendor/october/rain/src/Database/Model.php(428): October\Rain\Database\Model->extendableCall('allTemplates', Array)
#2 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1434): October\Rain\Database\Model->__call('allTemplates', Array)
#3 /Users/marco/Sites/up-studio/ie/plugins/rainlab/translate/classes/ThemeScanner.php(99): Illuminate\Database\Eloquent\Model::__callStatic('allTemplates', Array)
#4 /Users/marco/Sites/up-studio/ie/plugins/rainlab/translate/classes/ThemeScanner.php(38): RainLab\Translate\Classes\ThemeScanner->scanMailTemplatesForMessages()
#5 /Users/marco/Sites/up-studio/ie/plugins/rainlab/translate/classes/ThemeScanner.php(27): RainLab\Translate\Classes\ThemeScanner->scanForMessages()
#6 /Users/marco/Sites/up-studio/ie/plugins/rainlab/translate/controllers/messages.php(65): RainLab\Translate\Classes\ThemeScanner::scan()
#7 [internal function]: RainLab\Translate\Controllers\Messages->onScanMessages()
#8 /Users/marco/Sites/up-studio/ie/modules/backend/Classes/Controller.php(540): call_user_func_array(Array, Array)
#9 /Users/marco/Sites/up-studio/ie/modules/backend/Classes/Controller.php(423): Backend\Classes\Controller->runAjaxHandler('onScanMessages')
#10 /Users/marco/Sites/up-studio/ie/modules/backend/Classes/Controller.php(233): Backend\Classes\Controller->execAjaxHandlers()
#11 /Users/marco/Sites/up-studio/ie/modules/backend/Classes/BackendController.php(112): Backend\Classes\Controller->run('index', Array)
#12 [internal function]: Backend\Classes\BackendController->run('rainlab/transla...')
#13 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#15 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#16 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#17 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\Routing\Route->run()
#18 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Router.php(588): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#38 /Users/marco/Sites/up-studio/ie/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#39 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#40 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#41 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /Users/marco/Sites/up-studio/ie/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /Users/marco/Sites/up-studio/ie/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}
```

**Comment by LukeTowers** [comment]
What version of the RainLab.Translate plugin are you using and what build of October are you using?

**Comment by marcomessa** [comment]
@LukeTowers  I apologize for the stack.
These are my versions:

Octobercms: build 427
Translate: v 1.3.3

**Comment by mjauvin** [comment]
Resolved by https://github.com/octobercms/october/pull/3152
